# Generated by Django 4.2 on 2024-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=100)),
                ('queue_number', models.IntegerField()),
                ('time_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
